

(script startup capital_ship_flyover
	(test_all_doors_open)
	(sleep_until (volume_test_players ambient_carrier01_vol)1)
    (object_set_always_active capship01 TRUE)
	(scenery_animation_start capship01 objects\levels\atlas\l300\cov_capital_ship\cov_capital_ship entry)
	(object_set_custom_animation_speed capship01 0.5)
;	(sleep_until (volume_test_players ambient_carrier02_vol)1)
;	(object_set_custom_animation_speed capship01 0.2)
	
)

(script static void fly_asshole
    (object_set_always_active capship01 TRUE)
	(scenery_animation_start capship01 objects\levels\atlas\l300\cov_capital_ship\cov_capital_ship entry)
	(object_set_custom_animation_speed capship01 0.35)
)
(script static void test_all_doors_open
	(device_set_position_immediate highway_door_00 1)
	(device_set_position_immediate highway_door_01 1)
	(device_set_position_immediate highway_door_02 1)
	(device_set_position_immediate highway_door_03 1)
	(device_set_position_immediate highway_door_04 1)
	(device_set_position_immediate highway_door_05 1)
	(device_set_position_immediate highway_door_06 1)
	(device_set_position_immediate highway_door_07 1)
	(device_set_position_immediate highway_door_08 1)
	(device_set_position_immediate highway_door_09 1)
	(device_set_position_immediate highway_door_10 1)
	(device_set_position_immediate highway_door_11 1)
	(device_set_position_immediate highway_door_12 1)
	(device_set_position_immediate highway_door_13 1)
	(device_set_position_immediate highway_door_14 1)
	(device_set_position_immediate highway_door_15 1)
	(device_set_position_immediate highway_door_16 1)
	(device_set_position_immediate highway_door_17 1)
	(device_set_position_immediate highway_door_18 1)
	(device_set_position_immediate highway_door_19 1)
	(device_set_position_immediate highway_door_20 1)
	(device_set_position_immediate highway_door_21 1)
	(device_set_position_immediate highway_door_22 1)
	(device_set_position_immediate highway_door_23 1)
	(device_set_position_immediate highway_door_24 1)
	(device_set_position_immediate highway_door_25 1)
	(device_set_position_immediate highway_door_26 1)
	(device_set_position_immediate highway_door_27 1)
	(device_set_position_immediate highway_door_28 1)	
)